version: '3.4'
services:
  front:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/srv/app
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    tty: true
    depends_on:
      - back
  back:
    container_name: backend
    build:
      args:
        - NODE_ENV=prod
        - DBUSERNAME=${DBUSERNAME}
        - PASSWORD=${PASSWORD}
        - DATABASE=${DATABASE}
        - HOSTNAME=${HOSTNAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - SECRET=${SECRET}
        - API_BASE_URL=${API_BASE_URL}
        - APP_BASE_URL=${APP_BASE_URL}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      context: ../back
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3001:3001
      - 3443:3443
    environment:
      - NODE_ENV=prod
      - DBUSERNAME=${DBUSERNAME}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - HOSTNAME=${HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET=${SECRET}
      - API_BASE_URL=${API_BASE_URL}
      - APP_BASE_URL=${APP_BASE_URL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ../back/public/uploads:/usr/src/app/public/uploads
      - ../front/certbot/www:/var/www/certbot/:ro
      - ../front/certbot/conf/:/etc/ssl/:ro
    depends_on:
      - database
      - certbot
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      # - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
  database:
    image: postgres:15.3-alpine
    volumes:
      - database:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
volumes:
  database:
