name: Deploy Star Trail
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          private_key: ${{ secrets.SERVER_SSH_KEY }}
          scp_source: /
          scp_target: ${{ secrets.REMOTE_TARGET }}
          before_script: |
            df -h
          after_script: |
            whoami